apiVersion: v1
kind: Service
metadata:
  name: postgresql-metrics
  namespace: postgresql
  labels:
    cnpg.io/cluster: postgresql
spec:
  selector:
    cnpg.io/cluster: postgresql
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgresql-metrics
  namespace: postgresql
spec:
  rules:
    - host: postgresql-metrics.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgresql-metrics
                port:
                  number: 9187
